// Export all stores from a single entry point
export { useProductStore, type ProductStore } from "./product-store"
export { useCategoryStore, type CategoryStore } from "./category-store"
export { useEmployeeStore, type EmployeeStore } from "./employee-store"
export { useDepartmentStore, type DepartmentStore } from "./department-store"
export { useAuthStore, type AuthStore } from "./auth-store"
export { useCustomerStore, type CustomerStore } from "./customer-store"
export { useSaleStore, type SaleStore } from "./sale-store"
export { useSupplierStore, type SupplierStore } from "./supplier-store"
export { useStockStore, type StockStore } from "./stock-store"
export { useEventStore, type EventStore } from "./event-store"
export { useAttendanceStore, type AttendanceStore } from "./attendance-store"
export { useLeaveRequestStore, type LeaveRequestStore } from "./leave-request-store"
export { usePaymentStore, type PaymentStore } from "./payment-store"
export { useCartStore, type CartStore } from "./cart-store"
export { useRoleStore, type RoleStore } from "./role-store"
export { useNotificationStore, type NotificationStore } from "./notification-store"

export type { BaseStore, BaseEntity } from "@/types/store-types"
